---
title: "Random Forest - Test Set"
author: "Georgia Christodoulou"
output: html_document
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(tidyr)
library(tidyverse)
library(data.table)
library(caret)
library(ranger)
```

```{r}
# Read in data
application_train_smote <- as.data.frame(fread("data/application_train_smote.csv"))
application_test_clean <- as.data.frame(fread("data/application_test_clean.csv"))

# Confirm not the right column 
ncol(application_train_smote)
ncol(application_test_clean)

# Retain unique ID
SK_ID_CURR <- application_test_clean$SK_ID_CURR 

# Transform 
application_test_clean <- application_test_clean %>%   
  select(-SK_ID_CURR) %>%   
  mutate(across(where(is.character), ~factor(make.names(.))), across(where(is.logical), ~factor(ifelse(.,"Y","N"))))

# Create dummies
dummy <- dummyVars("~ .", application_test_clean)
application_test_dummy <- data.frame(predict(dummy, application_test_clean))

# About the right size
ncol(application_test_dummy)

# Get common column names
cols_to_keep <- intersect(names(application_test_dummy), names(application_train_smote))

# Finalize data sets
application_train_full <- application_train_smote |>
  select(all_of(c(cols_to_keep, "DEFAULT"))) |>
  mutate(DEFAULT = factor(DEFAULT, levels = c("Y", "N")))

application_test_full <- application_test_dummy %>% 
  select(all_of(c(cols_to_keep)))

# Confirm sizing
ncol(application_train_full)
ncol(application_test_full)
```


# Random Forest Model Predictions
```{r}
# train RF with 800 trees and 20 depth
rf_model_final <- ranger(formula = DEFAULT ~ ., data = application_train_full, 
                   num.trees = 800, max.depth = 20, oob.error = TRUE, probability = TRUE, importance = 'impurity', seed = 1234)
```


# Test Data Probabilities
```{r}
# probabilities on test data set
prob_test_final <- predict(rf_model_final, application_test_full, type = "response")$predictions[,2]

prob_test_final <- prob_test_final %>% round(2)

# combine probabilities with IDs
ID_probs <- data.frame(SK_ID_CURR, TARGET = prob_test_final)
```

# Write Probabilities to CSV
```{r}
# write to CSV file
write.csv(ID_probs, "credit_test_probabilities.csv", row.names = FALSE)
```

