---
title: "Modeling for Default | Performance Summary"
subtitle: "A summary of models evaluated to date and their performance modeling for default"
author: "Adam Bushman"
date: "2024-10-29"
format:
    html:
        embed-resources: true
execute:
    warning: false
---

```{r}
library('tidyverse')
```

Let's read in all the results of the various models we've experimented with.

```{r}
mcb1 <- read.csv('majority-class-baseline/model-results.csv')
elas <- read.csv('penalized-regression/model-results.csv')
svm <- read.csv('support-vector-machine/model-results.csv')
rf <- read.csv('random-forest/model-results.csv')
```

We then combine them into a single data frame we can use for plotting.

```{r}
full_results <- 
    bind_rows(
        mcb1, elas, svm, rf
    ) |>
    as_tibble()

full_results
```

We need to turn this into a along format. Also, we'll wrap the labels:

```{r}
full_results_long <- 
    pivot_longer(
        full_results, 
        cols = -c(model, hyperparameters)
    ) |>
    mutate(
        model = stringr::str_wrap(model, 15)
    )
```

Let's generate a basic, comparison plot across the various measures.

```{r}
ggplot(
    full_results_long, 
    aes(x = "1", y = value, label = paste0(model, " (", round(value,2) ,")"))
) +
    geom_label(
        aes(fill = model), 
        position = "jitter", 
        size = 2, 
        show.legend = FALSE
    ) +
    facet_wrap(~name, nrow = 1) +
    labs(
        title = "Modeling for default", 
        subtitle = "A summary of model performance"
    ) +
    theme_minimal() +
    theme(
        plot.title = element_text(face = "bold"), 
        plot.subtitle = element_text(face = "italic"), 
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        strip.text = element_text(face = "bold", color = "white"), 
        strip.background = element_rect(fill = "#707271", color = NA), 
        panel.background = element_rect(fill = NA, color = "black"), 
        panel.grid.major.x = element_blank()
    )
```